/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/swan.glb --types --transform 
Files: public/models/swan.glb [2.96MB] > C:\Users\Gus\repos\mdx-test\swan-transformed.glb [296.87KB] (90%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { type JSX } from 'react';

type GLTFAction = THREE.AnimationClip;

type GLTFResult = GLTF & {
    nodes: {
        swan: THREE.Mesh;
    };
    materials: {
        swan_Baked_BM: THREE.MeshStandardMaterial;
    };
    animations: GLTFAction[];
};

export function Swan(props: JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/models/swan.glb') as unknown as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.swan.geometry}
                material={materials.swan_Baked_BM}
                scale={[1, 1.188, 1]}
            />
        </group>
    );
}

useGLTF.preload('/models/swan.glb');
